language: node_js

sudo: false

node_js:
  - "node"

os:
  - linux

matrix:
  include:
    - os: linux
      env: CXX=clang++

install:
  - npm install

script:
  - npm lint
  - npm compile

cache:
  directories:
    - node_modules
